export enum Routes {
    Login = "/account/login",
    Register = "/account/register",
    Home = "/",
    Error = "/error/",
    CreateTournament = "/tournament/create",
    TournamentRegistration = "/tournament/registration/",
    TournamentInfo = "/tournament/",
    TournamentEdit = "/tournament/edit/",
    CreateTeam = "/team/create",
    TeamInfo = "/team/",
    EditTeam = "/team/edit/",
    CreateCategory = "/category/create",
    EditCategory = "/category/",
    User = "/user/",
    UserTeamApplications = "/user/team-applications",
}
